environment:

  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python27"
# TODO sgroat download libxml2 and libxslt
install:
  # We need wheel installed to build wheels
  - ps: Start-FileDownload "http://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"
  - setup-x86_64.exe --quiet-mode --no-shortcuts --only-site --root "C:\cygwin64" --site "http://cygwin.mirror.constant.com" --local-package-dir "C:\cygwin64\var\cache\setup" --packages "python-gtk2.0-devel,python2-libxml2,python2-pip" --upgrade-also
  - C:\cygwin64\bin\bash -lc "pip install pyserial nose mox"
  - C:\cygwin64\bin\bash -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && build/make_win32_build.sh"

build: off

test_script:
  # Put your test command here.
  # If you don't need to build C extensions on 64-bit Python 3.3 or 3.4,
  # you can remove "build.cmd" from the front of the command, as it's
  # only needed to support those cases.
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - run_all_tests.bat
