install:
  - ps: Start-FileDownload "http://cygwin.com/setup-x86.exe" -FileName "setup-x86.exe"
  - setup-x86.exe --quiet-mode --no-shortcuts --only-site --root "C:\cygwin" --site "http://cygwin.mirror.constant.com" --local-package-dir "C:\cygwin\var\cache\setup" --packages "python-gtk2.0-devel,python2-libxml2,python2-pip" --upgrade-also
  - C:\cygwin\bin\bash -lc "pip install pyserial nose mox pep8 pypiwin32"

build_script: C:\cygwin\bin\bash -lc "cd $(cygpath ${APPVEYOR_BUILD_FOLDER}) && build/make_win32_build.sh"

test_script: run_all_tests.bat
