language: generic
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
install: pip install .
