language: generic
os: linux
sudo: required
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
matrix:
  include:
    - os: osx
      before_install:
        - brew upgrade python
        - brew upgrade libxml2 --with-python
        - ln -s /usr/local/Cellar/libxml2/2.9.4/lbi/python2.7/site-packages/* /Library/Python/2.7/site-packages
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
