language: generic
os: linux
sudo: required
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
matrix:
  include:
    - os: osx
      install:
        - brew update
        - mkdir -p $(brew --repo)/Library/Taps/travis
        - ln -s $TRAVIS_BUILD_DIR/HomebrewFormula $(brew --repo)/Library/Taps/travis/homebrew-chirp
        - brew tap --repair
      script:
        - brew install travis/chirp/pango --with-x11
        # TODO compare with version in homebrew/core
    - os: osx
      before_install:
        - brew update
        - mkdir -p $(brew --repo)/Library/Taps/travis
        - ln -s $TRAVIS_BUILD_DIR/HomebrewFormula $(brew --repo)/Library/Taps/travis/homebrew-chirp
        - brew tap --repair
        - brew upgrade python
        - brew reinstall libxml2 --with-python && brew link --force libxml2
        - brew install travis/chirp/pango --with-x11
        - brew install libxslt pygtk
        - pip install pyserial nose mox
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
