language: python
version: 2.7
addons:
  apt:
    packages:
      - libxml2
      - libxml2-dev
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
virtual_env:
  system_site_packages: true
script: python setup.py install --record files.txt
