language: generic
os: linux
sudo: required
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
matrix:
  include:
    - os: osx
      before_install:
        - brew upgrade python
        - brew reinstall libxml2 --with-python && brew link --force libxml2
        - brew install libxslt pango
        - pip install pyserial
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
