language: generic
sudo: required
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
