language: generic
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      before_install:
        - brew update && brew bundle
        - pip install pyserial nose mox
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
