language: generic
os: linux
sudo: required
addons:
  apt:
    packages:
      - python
      - python-gtk2
      - python-libxml2
      - python-libxslt1
      - python-serial
      - python-suds
      - python-support
matrix:
  include:
    - os: osx
      before_install: brew uninstall libxml2 && brew install libxml2 --with-python
install: sudo python setup.py install --record files.txt
script: ./run_all_tests.sh
